In [1]:
import numpy as np

In [2]:
my_list= [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [12]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [13]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(5,25,5)

array([ 5, 10, 15, 20])